### ISSUE TITLE
Add Gif downloader to twitter

### ISSUE THREAD

**Issue by SundaraxKarma** [kinkenyuen/WeChatMomentVideoDwn#1]
can you please add a gif downloader to twitter please as when i try save gifs the app crashes

**Comment by kinkenyuen** [comment]
What iOS Version? I haven't make it Compatible with iOS 12 . Maybe you can downgrade Twitter to 7.40. Actually I didn't build this tweak for gifs dwn, just video,sry.

**Comment by kinkenyuen** [comment]
> can you please add a gif downloader to twitter please as when i try save gifs the app crashes

What iOS Version? I haven't make it Compatible with iOS 12 . Maybe you can downgrade Twitter to 7.40. Actually I didn't build this tweak for gifs dwn, just video,sry.

**Comment by SundaraxKarma** [comment]
ios 12.1.1 it crashes when press down on gifs and oh okay i was really hoping that you would add support to download gifs i would happily donate too if you could add gif download support and holding down on videos works perfect its just gifs

**Comment by kinkenyuen** [comment]
> ios 12.1.1 it crashes when press down on gifs and oh okay i was really hoping that you would add support to download gifs i would happily donate too if you could add gif download support and holding down on videos works perfect its just gifs

added Twitter GIF download, hope you like it

**Comment by kinkenyuen** [comment]
try version 1.1.2

2019年3月13日 上午3:01，SundaraxKarma <notifications@github.com> 写道：



ios 12.1.1 it crashes when press down on gifs and oh okay i was really hoping that you would add support to download gifs i would happily donate too if you could add gif download support and holding down on videos works perfect its just gifs
