### ISSUE TITLE
大神

### ISSUE THREAD

**Issue by ghost** [kinkenyuen/WeChatMomentVideoDwn#4]
A12设备，手机设置里的开关选项不显示。如何解决？

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by kinkenyuen** [comment]
> A12设备，手机设置里的开关选项不显示。如何解决？
> 
> Sent from [PPHub For GitHub](https://itunes.apple.com/cn/app/id1314212521)

我手上没有设备测试

**Comment by kinkenyuen** [comment]
> A12设备，手机设置里的开关选项不显示。如何解决？
> 
> Sent from [PPHub For GitHub](https://itunes.apple.com/cn/app/id1314212521)

安装preferenceloader依赖
